version: '2'
services:

  dusk_tests:
    image: php:7.1.1-cli
    command: tail -f /dev/null
    volumes:
      - ../:/User/mac/Places
    links:
      - selenium

  selenium:
    image: selenium/standalone-chrome:3.0.1-fermium
